### ISSUE TITLE
FutureSession deprecation warning

### ISSUE THREAD

**Issue by maciejstromich** [psquickitjayant/loggly-python-handler#10]
Project pins requests-futures in setup.py to be >=0.9.4 which with latest release of this package started to spam logs with 
```
`background_callback` is deprecated and will be removed in 1.0, use `hooks` instead
```

To fix this pin the requests-futures to 

requests-futures == 0.9.7

or update the code to use hooks dictionary instead of background_callback

**Comment by sseveringhaus-newclassrooms** [comment]
Another symptom of this issue is this message and a corresponding lack of log delivery to Loggly:
```
No handlers could be found for logger "FuturesSession"
```

**Comment by varshneyjayant** [comment]
@mostlyjason

**Comment by jewbetcha** [comment]
Came here to ask about this. Any workarounds or plans for another release?

**Comment by k12007** [comment]
There are a couple forks that already deal with this problem @jewbetcha

**Comment by jewbetcha** [comment]
Thank you!

**Comment by maciejstromich** [comment]
FYI: With requests-futures 1.0.0 released 14 days ago it stops the app from starting.

**Comment by varshneyjayant** [comment]
@maciejstromich  this repo is not longer maintained. Please open an issue at https://github.com/loggly/loggly-python-handler

Thanks
