### ISSUE TITLE
ssl error makes logging not work when frozen

### ISSUE THREAD

**Issue by selepo** [psquickitjayant/loggly-python-handler#2]
There is an issue with requests (and therefore also requests_futures) that if you freeze a python program, e.g. use py2exe or compile with nutika, the cacert.pem file is not found, which ends with an ssl error thrown. 

If the HTTPSHandler class would take an argument verify that defaults to true, and is propagated to the call: session.post(self.url, data=payload, verify=verify, background_callback=bg_cb) then one could in the case of need for freezing could add the filepath to cacert.pem in the setup of the HTTPSHandler.

Not sure if this would work via args in an ini file (e.g. use of logging.config.Fileconfig) or if you would need to make the call from source code.

**Comment by varshneyjayant** [comment]
See https://github.com/psquickitjayant/loggly-python-handler#configuration change the loggly url from https to http. It will work.
